# Biblioteca
```{r}
library(tidyverse)
library(rstatix)
library(ggsci)
library(here)
library(paletteer)
library(ggpubr)
# install.packages("paletteer")
```



# ELISA OD50
```{r fig.height=5, fig.width=10}
ELISA_OD50 <- read_excel("ELISA_OD50.xlsx")

table = ELISA_OD50 %>% 
  pivot_longer(cols = -dia,
               values_to = "value",
               names_to = "group") %>% 
  separate(group, into = c("group", "id"), "\\...") %>% 
  mutate(dia = as.factor(dia)) %>% 
  mutate(group = str_replace(group, pattern = "Vacina ", ""),
         group = str_replace(group, pattern = "Proteína ",  ""),
         group = fct_relevel(group, 
                             "PBS",
                             "ED-III",
                             "10 μg",
                             "25 μg",
                             "50 μg",
                             "Alum 10 μg",
                             "Alum 25 μg"
                             ))

```

## ANOVA e posthoc
```{r fig.height=7, fig.width=10}
library(rstatix)  # https://github.com/kassambara/rstatix
anova.res <- table %>%
  group_by(dia) %>%
  anova_test(value ~ group)

anova.res

stat.test.summary <- table %>%
  group_by(dia) %>%
  tukey_hsd(formula = value ~ group, detailed = T) %>% 
  add_xy_position(x = "group", 
                  dodge = 1) %>% 
  mutate(
    y.position = log10(y.position),
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    )
  )

stat.test.summary

stat.test = stat.test.summary %>% 
  group_by(dia) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
  mutate(y.position = min(y.position) + (row_number() - 1) * 0.1)


stat.test

#Definir comparações

#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = table %>%
  group_by(dia, group) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(group = paste0(group, " (n=", n, ")")) %>% 
  ggboxplot(x = "group",
      y = "value",
      fill = "group", 
      outlier.shape = NA,
      alpha = 0.5) +
  # geom_violin(color = "gray10",
  #             fill = NA,
  #             alpha = 1, 
  #             width = 1) +
  # geom_boxplot(outlier.shape = NA,
  #              alpha = 1, 
  #              width = 0.5) +

  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  scale_y_continuous(transform = "log10", 
                     labels = scales::label_log(base = 10),
                     breaks = c(0, 1, 10, 100, 1000, 10000)) +
  facet_wrap(~paste("Day ", dia)) +
   scale_fill_jama() +
    labs(fill = "Group",
       color = "Group",
       x = "",
       y = "OD50",
       title = "ELISA OD50% - All vs. All",
       subtitle =  "ANOVA, Tukey HSD. \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.",
       caption = get_pwc_label(stat.test.summary)) 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "ELISA_OD50_AllvsAll_Tukey.png"),
       width = 10,
       height = 7,
       bg = "white")
```


## Não paramétrico (Kruskal Wallis) e posthoc
### Por dia
```{r fig.height=7, fig.width=10}
library(rstatix) 
kruskal_wallis.summary <- table %>%
  group_by(dia) %>%
  kruskal_test(value ~ group)
  
kruskal_wallis.summary

stat.test = table %>% 
  group_by(dia) %>%
  dunn_test(value ~ group, 
            p.adjust.method = "BH", 
            detailed = T) %>% 
  add_xy_position(x = "group", 
                  dodge = 1) %>% 
  mutate(
    y.position = log10(y.position),
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    )
  ) %>% 
  group_by(dia) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
    mutate(y.position = min(y.position) + (row_number() - 1) * 0.1) 


stat.test


#Definir comparações


#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = table %>% 
  group_by(dia, group) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(group = paste0(group, " (n=", n, ")")) %>% 
  ggboxplot(x = "group",
      y = "value",
      fill = "group", outlier.shape = NA,
      alpha= 0.5) +
  # geom_violin(color = "gray10",
  #             fill = NA,
  #             alpha = 1, 
  #             width = 1) +
  # geom_boxplot(outlier.shape = NA,
  #              alpha = 1, 
  #              width = 0.5) +

  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  scale_y_continuous(transform = "log10", 
                     labels = scales::label_log(base = 10),
                     breaks = c(0, 1, 10, 100, 1000, 10000)) +
  facet_wrap(~paste("Day ", dia)) +
  scale_fill_jama() +
    labs(fill = "Group",
       color = "Group",
       x = "",
       y = "OD50",
       title = "ELISA OD50% - All vs. All ",
       subtitle =  "Kruskal-Wallis test (Benjamini-Hochberg correction). \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.") 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "ELISA_OD50_AllvsAll_Kruskal.png"),
       width = 10,
       height = 7,
       bg = "white")
```

### Por grupo
```{r fig.height=4, fig.width=10}
library(rstatix) 
kruskal_wallis.summary <- table %>%
  group_by(group) %>%
  kruskal_test(value ~ dia)
  
kruskal_wallis.summary

# stat.test = table %>% 
#   group_by(group) %>%
#   dunn_test(value ~ dia, 
#             p.adjust.method = "BH", 
#             detailed = T) %>% 
#   add_xy_position(x = "dia", 
#                   dodge = 1) %>% 
#   mutate(
#     y.position = log10(y.position),
#     p.adj.signif = case_when(
#       p.adj <= 0.01 ~ "***",       # p <= 0.01
#       p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
#       p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
#       TRUE ~ "ns"                        # p > 0.10
#     )
#   ) %>% 
#   group_by(group) %>% 
#   ungroup() %>% 
#     filter(!p.adj.signif %in% c("ns")) %>% 
#     mutate(y.position = min(y.position) + (row_number() - 1) * 0.1) 


stat.test


#Definir comparações


#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot_group = table %>% 
  # group_by(group, dia) %>% 
  # mutate(n = n()) %>% 
  # ungroup() %>% 
  # mutate(dia = paste0(dia, " (n=", n, ")")) %>% 
  ggboxplot(x = "dia",
      y = "value",
      fill = "group", outlier.shape = NA,
      alpha= 0.5) +
  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_kruskal_test(p.adjust.method = "BH", 
                     vjust = -2, label = "p = {p.format}",
                     hjust = 0.5, na.rm = T,
                     label.y.npc = "top",
                     label.x.npc = "center", size = 3) +
  # stat_pvalue_manual(stat.test,
  #                    label = "p.adj.signif",
  #                    hide.ns = T,
  #                    bracket.size = 0.3,
  #                    tip.length = 0.00,
  #                    vjust = 0.7
  #                    ) +
  scale_y_continuous(transform = "log10",
                     expand = c(0, 0.5),
                     labels = scales::label_log(base = 10),
                     breaks = c(0, 1, 10, 100, 1000, 10000)) +
  facet_wrap(~group, scales = "free_x", nrow = 1) +
  scale_fill_jama() +
    labs(fill = "Group",
       color = "Group",
       x = "",
       y = "OD50",
       title = "ELISA OD50% - By group ",
       subtitle =  "Kruskal-Wallis test (Benjamini-Hochberg correction). \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.") 

plot_group

plot_group %>%
ggsave(filename = here("Gráficos diversos", "ELISA_OD50_ByGroup_Kruskal.png"),
       width = 10,
       height = 4,
       bg = "white")
```

Unir plots
```{r fig.height=10, fig.width=10}
plot_united = plot / plot_group + plot_layout(axes = "collect",
                                axis_titles = "collect",
                                heights = c(1, 0.5)) +
  plot_annotation(title = "collect")


plot_united %>%
ggsave(filename = here("Gráficos diversos", "ELISA_OD50_ByGroup_ByDay_Kruskal.png"),
       width = 10,
       height = 10,
       bg = "white")
```



# IgG Subclasses
```{r fig.height=5, fig.width=10}
igg_subclasses <- read_excel(here("Gráficos diversos", "igg_subclasses.xlsx"))


table = igg_subclasses %>% 
  pivot_longer(cols = -Teste,
               values_to = "value",
               names_to = "group") %>% 
  clean_names() %>% 
  mutate(teste = as.factor(teste)) %>% 
  mutate(group = str_replace(group, pattern = "Vacina ", ""),
         group = str_replace(group, pattern = "Proteína ",  ""),
         group = fct_relevel(group, 
                             "PBS",
                             "ED-III",
                             "10 μg",
                             "25 μg",
                             "50 μg",
                             "Alum 10 μg",
                             "Alum 25 μg"
                             )) %>% 
  drop_na(value)
table
```

## ANOVA e Tukey post-hoc
```{r fig.height=5, fig.width=10}
library(rstatix)  # https://github.com/kassambara/rstatix
anova.res <- table %>%
  group_by(teste) %>%
  anova_test(value ~ group)

anova.res

stat.test.summary <- table %>%
  group_by(teste) %>%
  tukey_hsd(formula = value ~ group, detailed = T) %>% 
  add_xy_position(x = "group", 
                  dodge = 1) %>% 
  mutate(
    y.position = log10(y.position),
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    )
  )

stat.test.summary

stat.test = stat.test.summary %>% 
  group_by(teste) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
  mutate(y.position = min(y.position) + (row_number() - 1) * 0.1)


stat.test

#Definir comparações

#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = table %>% 
  group_by(teste, group) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(group = paste0(group, " (n=", n, ")")) %>% 
  ggboxplot(x = "group",
      y = "value",
      fill = "group", 
      outlier.shape = NA,
      alpha = 0.5) +
  # geom_violin(color = "gray10",
  #             fill = NA,
  #             alpha = 1, 
  #             width = 1) +
  # geom_boxplot(outlier.shape = NA,
  #              alpha = 1, 
  #              width = 0.5) +

  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  scale_y_continuous(transform = "log10", 
                     labels = scales::label_log(base = 10),
                     breaks = c(0, 1, 10, 100, 1000, 10000)) +
  facet_wrap(~teste) +
  scale_fill_jama() +
    labs(fill = "Group",
       color = "Group",
       x = "",
       y = "OD50",
       title = "ELISA IgG subclasses OD50% - All vs. All",
       subtitle =  "ANOVA, Tukey HSD. \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.",
       caption = get_pwc_label(stat.test.summary)) 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "ELISA_IgG_Subclasses_OD50_AllvsAll_Tukey.png"),
       width = 10,
       height = 7,
       bg = "white")
```


## Não paramétrico (Kruskal Wallis) e posthoc

```{r fig.height=7, fig.width=10}
library(rstatix) 
kruskal_wallis.summary <- table %>%
  group_by(teste) %>%
  kruskal_test(value ~ group)
  
kruskal_wallis.summary

stat.test = table %>% 
  group_by(teste) %>%
  dunn_test(value ~ group, 
            p.adjust.method = "BH", 
            detailed = T) %>% 
  add_xy_position(x = "group", 
                  dodge = 1) %>% 
  mutate(
    y.position = log10(y.position),
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    )
  ) %>% 
  group_by(teste) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
    mutate(y.position = min(y.position) + (row_number() - 1) * 0.1) 


stat.test


#Definir comparações

#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = table %>% 
  group_by(teste, group) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  mutate(group = paste0(group, " (n=", n, ")")) %>% 
  ggboxplot(x = "group",
      y = "value",
      fill = "group", outlier.shape = NA,
      alpha= 0.5) +
  # geom_violin(color = "gray10",
  #             fill = NA,
  #             alpha = 1, 
  #             width = 1) +
  # geom_boxplot(outlier.shape = NA,
  #              alpha = 1, 
  #              width = 0.5) +

  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  scale_y_continuous(transform = "log10", 
                     labels = scales::label_log(base = 10),
                     breaks = c(0, 1, 10, 100, 1000, 10000)) +
  facet_wrap(~teste) +
  scale_fill_jama() +
    labs(fill = "Group",
       color = "Group",
       x = "",
       y = "OD50",
       title = "ELISA - IgG - Subclasses - OD50% - All vs. All ",
       subtitle =  "Kruskal-Wallis test (Benjamini-Hochberg correction). \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.") 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "ELISA_IgG_Subclasses_OD50_AllvsAll_Kruskal.png"),
       width = 10,
       height = 7,
       bg = "white")
```









