---
title: "UPVacina"
output: html_document
date: "2024-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)

data="C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx"
excel_sheets(data) 

#BCG----
bcg_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "BCG")

#Wide to long
bcg=bcg_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(bcg_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#DTP1----

dtp1_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "DTP1")

#Wide to long
dtp1=dtp1_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(dtp1_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#DTP3----

dtp3_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "DTP3")

#Wide to long
dtp3=dtp3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(dtp3_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#HEPB3----

hepb3_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "HEPB3")

#Wide to long
hebp3=hepb3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(hepb3_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#HEPBB----

hepbb_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "HEPBB")

#Wide to long
hepbb=hepb3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(hepbb_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#HIB3----
hib3_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "HIB3")

#Wide to long
hib3=hib3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(hib3_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#IPV1----
ipv1_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "IPV1")

#Wide to long
ipv1=ipv1_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(ipv1_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#MCV1----
mcv1_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "MCV1")

#Wide to long
mcv1=mcv1_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(mcv1_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#MCV2----
mcv2_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "MCV2")

#Wide to long
mcv2=mcv2_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(mcv2_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")


#PCV3----
pcv3_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "PCV3")

#Wide to long
pcv3=pcv3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(pcv3_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#POL3----
pol3_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "POL3")

#Wide to long
pol3=pol3_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(pol3_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#RCV1----
rcv1_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "RCV1")

#Wide to long
rcv1=rcv1_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(rcv1_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#ROTAC----
rotac_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "ROTAC")

#Wide to long
rotac=rotac_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(rotac_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#YFV----
yfv_wide <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "YFV")

#Wide to long
yfv=yfv_wide %>%
  select(-unicef_region,-iso3,-vaccine) %>% 
  pivot_longer(-country,names_to = "year",values_to = "cov") %>% 
  inner_join(yfv_wide %>% 
               select(country,unicef_region,iso3,vaccine),by="country")

#regional_global----
regional_global <- read_excel("C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx", 
                                               sheet = "regional_global")
View(regional_global)
View(dtp1)

```



```{r}
#TENTATIVA DE LOOP PELO CHATGPT
library(tidyverse)
library(readxl)

data <- "C:/Users/PC/OneDrive/Área de Trabalho/UPVacina/Immunization coverage by antigen.xlsx"
sheets <- excel_sheets(data)

# Lista para armazenar os resultados
result_list <- list()

# Loop sobre todas as folhas
for (sheet in sheets) {
  # Leitura dos dados da folha atual
  wide_data <- read_excel(data, sheet = sheet)
  
  # Transformação de wide para long
  long_data <- wide_data %>%
    select(-unicef_region, -iso3, -vaccine) %>% 
    pivot_longer(-country, names_to = "year", values_to = "cov") %>% 
    inner_join(wide_data %>% 
                 select(country, unicef_region, iso3, vaccine), by = "country")
  
  # Armazenar o resultado na lista
  result_list[[sheet]] <- long_data
}

# Acesse os resultados usando result_list$<nome_da_folha>
# Por exemplo: result_list$BCG, result_list$DTP1, etc.
```

```{r}
#Pacote dplyr tem a função bind_rows()
install.packages("dplyr")
library("dplyr")

tabelageral<-bind_rows(bcg,
                       dtp1,
                       dtp3,
                       hebp3,
                       hepbb,
                       hib3,
                       ipv1,
                       mcv1,
                       mcv2,
                       pcv3,
                       pol3,
                       rcv1,
                       rotac,
                       yfv,
                       regional_global %>% 
                         mutate(year=as.character(year)))


#Salvar como objeto R - melhor pois mais leve
saveRDS(tabelageral,file="tabelageralunicef.rds")

#Salvar como arquivo excel
write.csv(tabelageral,file="tabelageralunicef.csv",row.names = F)

```
```{r}
brazil<-tabelageral %>% 
  filter(country=='Brazil')


install.packages("esquisse")
library(esquisse)

esquisser(brazil)

```


Tentar fazer:
- Gráficos para cada vacina para Brasil (Vacina x Ano)
- Comparar Brasil com Argentina

```{r}
#Gráfico cobertura vacinal BCG
plotbcg<-brazil %>%
 filter(vaccine %in% "BCG") %>%
 ggplot() +
  aes(x = year, y = cov) +
  geom_col(fill = "#4682B4") +
  labs(
    x = "Ano",
    y = "Cobertura (em %)",
    title = "Vacina BCG",
    subtitle = "Cobertura vacinal (em %) ao longo dos anos no Brasil."
  ) +
  ggthemes::theme_pander()

#Salvando plot BCG
ggsave(plotbcg,file="PlotBCG.png",width = 25,height = 10)

#Plot DTP1
plotdtp1<-brazil %>%
 filter(vaccine %in% "DTP1") %>%
 ggplot() +
  aes(x = year, y = cov) +
  geom_col(fill = "#4682B4") +
  labs(
    x = "Ano",
    y = "Cobertura (em %)",
    title = "Vacina DTP",
    subtitle = "Cobertura vacinal (em %) ao longo dos anos no Brasil."
  ) +
  ggthemes::theme_pander()

#Salvando plot DTP1
ggsave(plotdtp1,file="PlotDTP1.png",width = 25,height = 10)
```

```{r}
#Padronizando
data_long_standardized = data_long %>% 
  
  select(name = country, 
         country_abrev = iso3, 
         year, 
         vaccine, 
         coverage = cov, 
         region = unicef_region) %>% 
  
  
  
  mutate(
         # Anotando dados
         year = as.integer(year), #Aqui, converteremos year em número inteiro, para evitar que seja lido com decimais.
         type = if_else(name == region, # Se o nome for igual à região,
                        "region",       # então ele é uma região,
                        "country"),     # caso contrário, é um país.
         
         country_abrev = if_else(name == region, # Se o nome for igual à região,
                        name,       # então ele é uma região,
                        country_abrev),     # caso contrário, é um país.
         
         region = if_else(is.na(region), 
                          name, 
                          region),
         
         # Vacinas por doenças
         diseases = case_when(vaccine == "BCG" ~ "Tuberculosis",
                              vaccine == "DTP1" ~ "Difteria, Tetanus, Pertussis",
                              vaccine == "DT3" ~ "Difteria, Tetanus, Pertussis",
                              vaccine == "HEPB3" ~ "Hepatitis B",
                              vaccine == "HEPBB" ~ "Hepatitis B",
                              vaccine == "HIB3" ~ "Haemophilus influenzae B",
                              vaccine == "IPV1" ~ "Poliomielitis",
                              vaccine == "MCV1" ~ "Measles",
                              vaccine == "MCV2" ~ "Measles",
                              vaccine == "PCV3" ~ "Pneumococcus",
                              vaccine == "POL3" ~ "Poliomielitis",
                              vaccine == "RCV1" ~ "Rotavirus",
                              vaccine == "ROTAC" ~ "Rotavirus",
                              vaccine == "YFV" ~ "Yellow fever",
                              TRUE ~ vaccine
                              ),
         
         
         # Abreviação para nome completo
         region_complete = case_when(region == "EAPR" ~ "East Asia and Pacific", 
                              region == "ECAR" ~ "Europe and Central Asia",
                              region == "MENA" ~ "Middle East and North Africa",
                              region == "ESAR" ~ "Eastern and Southern Africa",
                              region == "LACR" ~ "Latin America and Caribbean",
                              region == "Non-programme" ~ "Non-programme",
                              region == "ROSA" ~ "South Asia",
                              region == "WCAR" ~ "West and Central Africa",
                              TRUE ~ region
  ))

#Salvar tabela

data_long_standardized %>% 
  write_csv(file = "cobertura_vacinal_unicef_padronizada.csv", row.names = F)
```


```{r}
#Tabela com vacinação
data_long_standardized = readRDS(file = "cobertura_vacinal_unicef_padronizada.rds")
data_long_standardized

#Tabela com dados gerais de paises
paises_anotados = readRDS(file = "paises_anotados.rds")
paises_anotados

#Unindo tabelas
data_long_annotated = data_long_standardized %>% 
  inner_join(paises_anotados, by = "name")

glimpse(data_long_annotated) #Colunas duplicadas

data_long_annotated = data_long_standardized %>% 
  inner_join(paises_anotados %>% 
               select(-region_complete), by = "name") %>% 
  mutate(name = if_else(name == continent, region_complete, name))
  
data_long_annotated %>% 
  saveRDS(file = "cobertura_vacinal_anotada.rds")

```




