---
output: 
  html_document: 
    toc: yes
---





# Importar de bibliotecas
```{r}
library(tidyverse)
library(rstatix)
library(ggsci)
library(here)
library(paletteer)
library(ggpubr)
library(readxl)
library(janitor)
library(patchwork)
library(ggforce)
library(ggh4x)
# install.packages("paletteer")
```



# Citometria

Limpeza de dados
```{r fig.height=5, fig.width=10}
dados_citometria_AL <- read_csv(here("Gráficos diversos", "Aline", "dados_citometria_AL.csv"))

citometria_clean = dados_citometria_AL %>% 
  clean_names() %>% 
  mutate(porcentagem = str_replace(porcentagem, ",", ".") %>% 
           as.numeric(),
         experimento = case_when(str_detect(amostra, "Exp 2") ~ "Exp 2",
                                 str_detect(amostra, "Exp 3") ~ "Exp 3",
                                 str_detect(amostra, "Alum") ~ "Exp 4",
                                 str_detect(amostra, "CpG") ~ "Exp 4",
                                 TRUE ~ "Exp 1"),
         amostra = str_remove(amostra, "Exp 2"),
         amostra = str_remove(amostra, "Exp 3"),
         animal = str_extract(amostra, "(?<=\\s)\\d+"),
         grupo = str_squish(str_remove(amostra, "\\s\\d+")),
         tipo = case_when(str_detect(grupo, "V10") ~ "V10",
                          str_detect(grupo, "V20") ~ "V20",
                          str_detect(grupo, "V30") ~ "V30",
                          str_detect(grupo, "V50") ~ "V50",
                          T~grupo),
         amostra = fct_relevel(amostra, "PBS", "Qb", "PBS"))
  # group_by(grupo, experimento, teste) %>% 
  # mutate(n = n()) %>% 
  # ungroup() %>% 
  # mutate(grupo_n = paste0(grupo, " (n=", n, ")")) %>% 
  # arrange(amostra, teste)

citometria_clean %>% 
  count(tipo)
  
```

```{r fig.height=10, fig.width=10}
#Identificar outliers
citometria_clean %>% 
  group_by(grupo, teste) %>% 
  identify_outliers(porcentagem) 


#Variancias são iguais (homosquedacidade)?
citometria_clean %>% 
  group_by(teste, grupo) %>% 
  levene_test(porcentagem ~ grupo) %>% 
  mutate(homo = ifelse(p > 0.05, "Yes", "No"))
```


## Barras (contorno) + IC (brackets) + Pontos
```{r fig.height=10, fig.width=10}

citometria_clean_ic = citometria_clean %>% 
    ggplot() +
  aes(x = grupo,
      y = porcentagem,
      color = tipo) +
  geom_col(aes(x = grupo,
               y = mean,
               color = tipo),
           fill = NA,
           data = citometria_clean %>% 
             group_by(teste, grupo) %>% 
             summarize(mean = mean(porcentagem, na.rm = T),
                       tipo = tipo) %>% 
             ungroup() %>% 
             distinct()
           ) +
    stat_summary(geom = "errorbar",
               fun.data = mean_cl_boot, #Bootstrapped
               position = "dodge",
               width=.2,
               size = 0.4,
               alpha = 1,
               color = "black") +
    #Parametrizado
    # stat_summary(geom = "crossbar", 
    #            fun.data = mean_se, 
    #            position = "dodge", 
    #            # width=.5, 
    #            # size = 1,
    #            alpha = 0.5,
    #            color = "black") +
    #Média
    # stat_summary(fun.y = mean,
    #            geom = "point",
    #            color = "red") +
    geom_sina(aes(shape = experimento),
              size = 1.5, #or geom_jitter(position = position_dodge(width = 0.1))
             stroke = 0.4,
             # color = "black",
             alpha = 1,
             # shape=21,
             show.legend = T) +
  facet_wrap2(~teste, scales = "free_y", axes = "all", nrow = 3) +
  theme_minimal() +
    theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "right",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.background = element_rect(fill = NA,
                                        color = NA),
        strip.text = element_text(size = 10,
                                  color = "black"),
        strip.text.y = element_text(size = 10,
                                  color = "black",
                                  angle = 0),
        axis.line = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  scale_y_continuous(expand = c(0.01,0.01)) +
  scale_fill_npg() +
  scale_color_npg() +
  # guides(fill = guide_legend(nrow = 1)) +
      labs(title = "Distribuição dos Valores por Grupo, Citometria",
       subtitle = "IC95%",
       x = "Grupos",
       y = "Percentual",
       fill = "Grupos",
       shape = "Experimentos") 


citometria_clean_ic


```

## Barras (Transparente) + IC (brackets) + Pontos
```{r fig.height=10, fig.width=10}

citometria_clean_ic = citometria_clean %>% 
    ggplot() +
  aes(x = grupo,
      y = porcentagem,
      color = tipo) +
  geom_col(aes(x = grupo,
               y = mean,
               fill = tipo),
           color = NA,
           alpha = 0.4,
           data = citometria_clean %>% 
             group_by(teste, grupo) %>% 
             summarize(mean = mean(porcentagem, na.rm = T),
                       tipo = tipo) %>% 
             ungroup() %>% 
             distinct()
           ) +
    stat_summary(geom = "errorbar",
               fun.data = mean_cl_boot, #Bootstrapped
               position = "dodge",
               width=.2,
               size = 0.4,
               alpha = 1,
               color = "black") +
    #Parametrizado
    # stat_summary(geom = "crossbar", 
    #            fun.data = mean_se, 
    #            position = "dodge", 
    #            # width=.5, 
    #            # size = 1,
    #            alpha = 0.5,
    #            color = "black") +
    #Média
    # stat_summary(fun.y = mean,
    #            geom = "point",
    #            color = "red") +
    geom_sina(aes(shape = experimento),
              size = 1.5, #or geom_jitter(position = position_dodge(width = 0.1))
             stroke = 0.4,
             # color = "black",
             alpha = 1,
             # shape=21,
             show.legend = T) +
  facet_wrap2(~teste, scales = "free_y", axes = "all", nrow = 3) +
  theme_minimal() +
    theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "right",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.background = element_rect(fill = NA,
                                        color = NA),
        strip.text = element_text(size = 10,
                                  color = "black"),
        strip.text.y = element_text(size = 10,
                                  color = "black",
                                  angle = 0),
        axis.line = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  scale_shape_manual(values = c(15, 16,17,1)) +
  scale_y_continuous(expand = c(0.01,0.01)) +
  scale_fill_npg() +
  scale_color_npg() +
      labs(title = "Distribuição dos Valores por Grupo, Citometria",
       subtitle = "IC95%",
       x = "Grupos",
       y = "Percentual",
       fill = "Grupos",
       color = "Grupos",
       shape = "Experimentos") 


citometria_clean_ic


```



## Normality test

```{r fig.height=5, fig.width=10}


#Teste de Shapiro-Wilk
## p<0.05: Não-normal
## p>0.05: Normal
citometria_clean %>% 
  group_by(grupo, teste, marcador) %>% 
  shapiro_test(value) %>% 
  mutate(normal = ifelse(p > 0.05, "Yes", "No"))


# Q-Q Plot
citometria_clean %>% 
ggplot(aes(sample = valor,
           color = grupo)) +
  scale_x_continuous(expand = c(0.1,0.1), 
                     n.breaks = 2
                     ) +  
  stat_qq() +
  stat_qq_line() +
facet_grid(~teste~marcador~grupo, scales = "free_y") +
  theme_minimal() +
  scale_color_jama() +
    theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        panel.spacing.x = unit(1, "lines"),
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line = element_line(color = "black",
                                   size = 0.5),
        axis.ticks = element_line(color = "black",
                                  size = 0.5),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  labs(x = "",
       y = "",
       title = "Q-Q Plot - Normality test")


```


## ANOVA e posthoc

### CD4
```{r fig.height=7, fig.width=10}

#CD4
anova.res_cd4 <- citometria_clean %>%
  filter(teste == "CD4") %>% 
  welch_anova_test(valor ~ grupo)

anova.res_cd4

stat.test.summary_cd4 <- citometria_clean %>%
  filter(teste == "CD4") %>% 
  group_by(marcador) %>%
  games_howell_test(formula = valor ~ grupo, detailed = T) %>% 
  add_xy_position(x = "grupo", 
                  dodge = 1) %>% 
  mutate(
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    ),
    teste = "CD4"
  )

stat.test_cd4 = stat.test.summary_cd4 %>% 
  group_by(marcador) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
  mutate(y.position = min(y.position) + (row_number() - 1) * 0.1)

# Effect size
effect_size_cd4 = citometria_clean %>%
  filter(teste == "CD4") %>% 
  group_by(marcador) %>%
  cohens_d(valor ~ grupo, var.equal = F) %>% 
  mutate(effsize = round(effsize, 1),
         teste = "CD4") 

stat.test_cd4 = effect_size_cd4 %>% 
  select(group1:marcador, magnitude, teste) %>% 
  inner_join(stat.test.summary_cd4, by = join_by(teste, group1, group2, marcador))

stat.test_cd4
```


### CD8
```{r fig.height=7, fig.width=10}

#CD4
anova.res_cd8 <- citometria_clean %>%
  filter(teste == "CD8") %>% 
  welch_anova_test(valor ~ grupo)

anova.res_cd8

stat.test.summary_cd8 <- citometria_clean %>%
  filter(teste == "CD8") %>% 
  group_by(marcador) %>%
  games_howell_test(formula = valor ~ grupo, detailed = T) %>% 
  add_xy_position(x = "grupo", 
                  dodge = 1) %>% 
  mutate(
    p.adj.signif = case_when(
      p.adj <= 0.01 ~ "***",       # p <= 0.01
      p.adj <= 0.05 ~ "**",        # 0.01 < p <= 0.05
      p.adj <= 0.10 ~ "*",         # 0.05 < p <= 0.10
      TRUE ~ "ns"                        # p > 0.10
    ),
    teste = "CD8"
  )

stat.test_cd8 = stat.test.summary_cd8 %>% 
  group_by(marcador) %>% 
  ungroup() %>% 
    filter(!p.adj.signif %in% c("ns")) %>% 
  mutate(y.position = min(y.position) + (row_number() - 1) * 0.1)

# Effect size
effect_size_cd8 = citometria_clean %>%
  filter(teste == "CD8") %>% 
  group_by(marcador) %>%
  cohens_d(valor ~ grupo, var.equal = F) %>% 
  mutate(effsize = round(effsize, 1),
         teste = "CD8") 

stat.test_cd8 = effect_size_cd8 %>% 
  select(group1:marcador, magnitude, teste) %>% 
  inner_join(stat.test.summary_cd8, by = join_by(teste, group1, group2, marcador))

stat.test_cd8
```


### CD4
```{r fig.height=7, fig.width=10}
#Definir comparações

#Mostrar somente as comparações significantes
my_comparisons <- stat.test %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = citometria_clean %>%
  filter(teste == "CD4") %>% 
  ggboxplot(x = "grupo",
      y = "valor",
      fill = "grupo", 
      outlier.shape = NA,
      alpha = 0.5) +
  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  facet_wrap(~marcador) +
   scale_fill_jama() +
    labs(fill = "Grupo",
       color = "Group",
       x = "Grupo",
       y = "MFI",
       title = "Citometria - CD4 - All vs. All",
       subtitle =  "Welch's ANOVA, Games-Howell post-hoc test. \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.",
       caption = get_pwc_label(stat.test.summary)) 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "Citometria_AllvsAll_Welch_GamesHowell_CD4.png"),
       width = 10,
       height = 7,
       bg = "white")


```


###CD8

```{r fig.height=7, fig.width=10}
#Definir comparações

#Mostrar somente as comparações significantes
my_comparisons <- stat.test_cd8 %>%
  select(group1, group2) %>% 
  arrange(group1) %>% 
  distinct() %>% 
  rowwise() %>%
  mutate(comparison = list(c(group1, group2))) %>%
  pull(comparison)

plot = citometria_clean %>%
  filter(teste == "CD8") %>% 
  ggboxplot(x = "grupo",
      y = "valor",
      fill = "grupo", 
      outlier.shape = NA,
      alpha = 0.5) +
  stat_summary(fun.y= mean, 
               geom="point", 
               shape=95, 
               size=3, 
               color="red",
               stroke = 5,
               # fill="red", 
               alpha = 1,
               show.legend = F) +
    geom_point(fill = NA,
               color = "black",
             size = 1,
             stroke = 1,
             alpha = 1,
             shape=21, 
             show.legend = F) +
  theme_minimal() +
  theme(text = element_text(size = 10,
                            color = "black"),
        plot.caption = element_text(size = 10, 
                                    color = "black",
                                    hjust = 0.5),
        legend.position = "none",
        axis.text.x = element_text(angle = 45,
                                   size = 10,
                                   hjust = 1,
                                   vjust = 1,
                                   color = "black"),
        axis.text.y = element_text(size = 10,
                                   color = "black"),
        strip.text = element_text(size = 12,
                                  color = "black"),
        axis.line.x = element_line(color = "black",
                                   size = 1),
        axis.ticks.x = element_line(color = "black",
                                  size = 1),
        panel.grid = element_line(linetype = 2,
                                  color = "gray90")) +
  stat_pvalue_manual(stat.test,
                     label = "p.adj.signif", 
                     hide.ns = T, 
                     bracket.size = 0.3, 
                     tip.length = 0.00, 
                     vjust = 0.7
                     ) +
  facet_wrap(~marcador) +
   scale_fill_jama() +
    labs(fill = "Grupo",
       color = "Group",
       x = "Grupo",
       y = "MFI",
       title = "Citometria - CD8 - All vs. All",
       subtitle =  "Welch's ANOVA, Games-Howell post-hoc test. \nSignificance p-value symbols: * = 0.10, ** = 0.05, *** = < 0.01. Red lines correspond to the mean.",
       caption = get_pwc_label(stat.test.summary)) 

plot

plot %>%
ggsave(filename = here("Gráficos diversos", "Citometria_AllvsAll_Welch_GamesHowell_CD8.png"),
       width = 10,
       height = 7,
       bg = "white")


```
```


